### ISSUE TITLE
Notice: Charitable_Form::render_field is deprecated

### ISSUE THREAD

**Issue by helgatheviking** [Charitable/Charitable#568]
>Notice: Charitable_Form::render_field is <strong>deprecated</strong> since version 1.5.0 of Charitable! Use Charitable_Public_Form_View::render_field() instead. in C:\Users\helga\Websites\jen.criticalink.test\wp-content\plugins\Charitable\includes\deprecated\class-charitable-deprecated.php on line 123

This appears to be coming from [`add_action( 'charitable_form_field', array( $this, 'render_field' ), 10, 6 );`](https://github.com/Charitable/Charitable/blob/master/includes/forms/class-charitable-donation-form.php#L125) and maybe it is also there in other forms as I see that `add_action` in several constructors. 

It is called in the views class [here](https://github.com/Charitable/Charitable/blob/master/includes/forms/views/class-charitable-public-form-view.php#L277).

**Comment by ericnicolaas** [comment]
@helgatheviking Still seeing this with the latest master?

**Comment by helgatheviking** [comment]
No, seems to have been resolved.

**Comment by lesles08** [comment]
Why am I still seeing this error? I am up to date on the plugin....
https://honor.gift/honor.gift/artthisweek/campaigns/help-poor-peoples-in-india/donate/
