### ISSUE TITLE
Allow drag and drop of meta boxes on the campaign screen

### ISSUE THREAD

**Issue by ericnicolaas** [Charitable/Charitable#602]
The fact that we disallow this has unintended consequences with some other plugins:

>I have Yoast SEO plugin installed and the box always appears before the campaign details setting box, but I cannot drag any of it to another position

**Comment by helgatheviking** [comment]
This appears to have been fixed?

**Comment by ericnicolaas** [comment]
This isn't fixed, but my eventual plan is to shift to using the block editor, so I'd rather focus my energy on that.
